# ======================================
# starship.toml
# ======================================

format = """
$os\
$sudo\
$username\
$hostname\
$custom\
$direnv\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$conda\
$python\
$lua\
$rust\
$java\
$docker_context\
$kubernetes\
$line_break\
$line_break\
$character\
"""

right_format = """
$cmd_duration\
$time\
"""

[os.symbols]
Macos = " ÔÖπ "
Linux = " Û∞åΩ "
Ubuntu = " Ôåõ "
Debian = " ÔåÜ "

[os]
disabled = false
format = """
[ÓÇ∫](fg:#89b4fa)\
[$symbol]($style)\
[ÓÇº](fg:#89b4fa)\
"""
style = "fg:#313244 bg:#89b4fa"

[sudo]
disabled = false
symbol = ' Û∞øÜ sudo'
format = """
[ÓÇ∫](fg:#eba0ac)\
[$symbol]($style)\
[ÓÇº](fg:#eba0ac)\
"""
style = "bold fg:#313244 bg:#eba0ac "


[username]
style_user = "bold fg:#313244 bg:#f9e2af"
style_root = "bold fg:#313244 bg:#f9e2af"
format = """
[ÓÇ∫](fg:#f9e2af)\
[ $user ]($style)\
[ÓÇº](fg:#f9e2af)\
"""
disabled = false
show_always = true

[hostname]
ssh_only = true
style = "bold fg:#313244 bg:#f9e2af"
format = """
[ÓÇ∫](fg:#f9e2af)\
[ $hostname ]($style)\
[ÓÇº](fg:#f9e2af)\
"""
disabled = false

[custom.venv]
command = "basename \"$VIRTUAL_ENV\""
when = "test -n \"$VIRTUAL_ENV\""
format = """
[ÓÇ∫](fg:#cba6f7)\
[$output]($style)\
[ÓÇº](fg:#cba6f7)\
"""
style = "bold fg:#313244 bg:#cba6f7"

[direnv]
disabled = false
format = """
[ÓÇ∫](fg:#89dceb)\
[$symbol$allowed]($style)\
[ÓÇº](fg:#89dceb)\
"""
style = "bold fg:#313244 bg:#89dceb"

[directory]
style = "bold fg:#313244 bg:#b4befe"
read_only_style = 'bold fg:#313244 bg:#b4befe'
truncation_length = 6
truncation_symbol = "ÔÅº"
truncate_to_repo = false
home_symbol = 'Û∞ãû ~'
read_only = 'Û∞åæ '
format = """
[ÓÇ∫](fg:#b4befe)\
[ $path ]($style)\
[$read_only]($read_only_style)\
[ÓÇº](fg:#b4befe)\
"""

[git_branch]
symbol = 'ÔÑ¶ '
truncation_length = 12
truncation_symbol = ''
style = 'bold fg:#89dceb bg:#45475a'
format = """
[ÓÇ∫](fg:#45475a)\
[ $symbol$branch(:$remote_branch) ]($style)\
"""

[git_status]
disabled = false
style = 'bold fg:#eba0ac bg:#45475a'
conflicted = '='
ahead = '‚á°${count}'
behind = '‚á£${count}'
diverged = '‚áï'
up_to_date = '‚úì'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '¬ª'
deleted = '‚úò'
format = """
[ÓÇª Ó∏Ω ](fg:#89dceb bg:#45475a)\
[$all_status$ahead_behind ]($style)\
"""

[git_metrics]
disabled = false
added_style = 'bold fg:#a6e3a1 bg:#45475a'
deleted_style = 'bold fg:#89b4fa  bg:#45475a'
format = """
[ÓÇª ÔëÄ ](fg:#89dceb bg:#45475a)\
[+$added]($added_style)[-$deleted ]($deleted_style)[ÓÇº](fg:#45475a)\
"""

[fill]
symbol = '.'
style = 'fg:#89b4fa) bg:none'

[python]
pyenv_version_name = false
symbol = '[Óúº ](fg:#f9e2af bg:#8093fd)'
format = '[ÓÇ∫](fg:#8093fd)[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)[ÓÇº](fg:#8093fd)'
style = 'bold fg:#313244 bg:#8093fd'

[lua]
symbol = "[Óò† ](fg:#1e66f5 bg:#89b4fa)"
format = '[ÓÇ∫](fg:#89b4fa)[ ${symbol}(${version}) ]($style)[ÓÇº](fg:#89b4fa)'
style = 'bold fg:#313244 bg:#89b4fa'

[rust]
symbol = "[Û±òó ](fg:#e64553 bg:#eba0ac)"
format = '[ÓÇ∫](fg:#eba0ac)[ ${symbol}(${version}) ]($style)[ÓÇº](fg:#eba0ac)'
style = 'bold fg:#313244 bg:#eba0ac'

[nodejs]
symbol = "‚¨¢ "
format = '[ÓÇ∫](fg:#eba0ac)[ ${symbol}(${version}) ]($style)[ÓÇº](fg:#eba0ac)'
style = "bold fg:#313244 bg:#34c324"

[java]
symbol = "‚òï "
format = '[ÓÇ∫](fg:#eba0ac)[ ${symbol}(${version}) ]($style)[ÓÇº](fg:#eba0ac)'
style = "bold fg:#313244 bg:#e03131"

[docker_context]
symbol = "üê≥ "
format = '[ÓÇ∫](fg:#eba0ac)[ ${symbol}(${version}) ]($style)[ÓÇº](fg:#eba0ac)'
style = "bold fg:#313244 bg:#2b1cd4"

[kubernetes]
format = '[ÓÇ∫](fg:#eba0ac)[‚õµ $context \($namespace\) ]($style)[ÓÇº](fg:#eba0ac)'
style = "bold fg:#313244 bg:#e8f436"
disabled = false

[cmd_duration]
show_milliseconds = true
min_time = 100
format = '[Û∞ûå $duration  ](fg:#f9e2af)'

[time]
disabled = false
format = '[Ôê∫ $time](bold fg:#6c7086)'
time_format = '%T'

[character]
success_symbol = "[‚ûú](bold green)"
error_symbol = "[‚ûú](bold red)"
vicmd_symbol = "[V](bold green)"
